# Renauld Mounia-Cecile, Christopher Piche-Frattaroli
# Date 2021-11-07
 
- name: Tâche 1
  hosts: all
  become: true
  vars_files: ./mdpvoute.yml
  tasks:
        - name: Mise a jour 
          command: "apt update -y"
          command: "apt upgrade -y"
